### ISSUE TITLE
Initial DIGH402 Proposal Discussion 

### ISSUE THREAD

**Issue by RJP43** [RJP43/PlainTextPodcast#1]
## Team Members: 
Rebecca Parker @RJP43
Taylor Brown @taylorcate
  
## Proposal Elevator Pitch:  
The Loyola Digital Humanities Master’s Program is unique in being one of the few purely Digital Humanities graduate programs in the world. Considering the glaring absence of Digital Humanities specific podcasts and Loyola’s unique DH MA status the 2017 DH cohort decided it would be worthwhile to launch a DH podcast run by the DH MA graduate students. Currently, the cohort meets almost every Wednesday with the CTSDH faculty for #DebatingDH, a casual conversation led by one of the graduate students or faculty members on a specific Digital Humanities article/book chapter. The cohort will move forward with creating the podcast by utilizing these sessions to plan, record, and edit the podcast episodes. Each episode will be centered around a topic similar to how the #DebatingDH conversations have been centered around a particular reading. Our hope is that by starting this podcast as a part of the 2017-2018 Digital Humanities Graduate Student Initiative that we can instill a lasting hallmark related to receiving the DH MA at Loyola University Chicago.  While the DH podcast is an ongoing project idea, there are technical aspects of the project that will need designing and creating prior to releasing the podcast publically.   
  
The primary task that needs to be completed prior to launch (next to the actual recording of the podcast) and the focus of this project proposal will be to create the podcast's website. @taylorcate and I have determined it would be worthwhile to consider the possibilities of hosting the podcast out of [GitHub Pages](https://pages.github.com/).  The episodic nature of the podcast lends itself well to the use of a static HTML generator along the lines of Nieky's lecture last class (2018-02-30) because while the content will change episode to episode we envision the episode pages to be technically identical.  It will be ideal to come up with a system of updating the podcast website with a new episode and its content without having to hand-code the HTML/CSS/JavaScript every time.  In addition to the convenience a static website would bring, we want to be sure we are conforming to level Double-A of the [World Wide Web Consortium (W3C) Web Content Accessibility Guidelines 2.0](https://www.w3.org/WAI/intro/wcag). These guidelines explain how to make web content more accessible for people with disabilities. We feel that if we spend enough time developing a static website using the principals of universal design and adhering to the WCAG AA standards, it will help ensure consistency in the podcast's accessibility.

In addition to this primary focus on creating an accessible, static website, @taylorcate and I have started discussing other ways we can incorporate programming into the regular functions of the podcast. An aspect of the podcast we are both interested in harnessing to its fullest potential will be its social media promotion and engagement. In this regard, we are interested in mining Digital Humanities and Computer Science tweets for themes/topics that can be incorporated into the podcast's episodes. We imagine web scraping, the Twitter API,  and basic topic modeling will be the technologies necessary to make this possible. In addition to scraping other people's tweets/conversations, we are interested in the idea of creating a Twitter Bot on behalf of the podcast that helps generate conversations that simultaneously engage the larger Twitter universe with the podcast's production and provides the DH cohort with relative, themed material to respond to in the podcast episodes.

**Comment by RJP43** [comment]
Please note we are open to **one** other person joining our team. We think a team larger than three people working on the design of this project will result in too many cooks in the kitchen and will delay the project's progre.ss. The project will already be incorporating the ideas of the larger DH 2017 cohort because of the group's role in recording the podcast; therefore, we would like to keep this development and design team small.

**Comment by gkthiruvathukal** [comment]
I really like this project idea. It would be great if you can figure out how to build your idea around something simple like the Jekyll project, which is a great static website generator that can be hosted on GitHub Pages. See https://jekyllrb.com/.

**Comment by RJP43** [comment]
@gkthiruvathukal I mentioned Jekyll to @taylorcate yesterday. I have looked into the Jekyll project in the past, but never had an opportunity to actually develop anything using it or in the wheelhouse of what @dallen4 discussed last class. Glad you are overall on board with our ideas 😊

**Comment by taylorcate** [comment]
@RJP43 obviously has the technical chops to conquer this project idea, so I'm going to try to keep up with her and see if we can't make a really interesting and accessible host site for Plain.txt. Thank you Dr. Thiruvathukal for approving our project! As of right now I would like to center my approach to the project through more of a design lens, however, as my technical skills improve I'm sure I will have more to offer in the actual creation of the site and its features. My GitHub skills are already improving! lol See you both in class.

**Comment by dallen4** [comment]
https://github.com/cnunciato/jekyll-soundcloud
